# Generated by Django 5.0.1 on 2024-01-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='description',
        ),
        migrations.AddField(
            model_name='contractor',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
